<?php
include __DIR__ . '/../layout/header.php';
include __DIR__ . '/../layout/sidebar.php';

$guideInfo = $data['guide_info'] ?? [];
$lichLamViec = $data['lich_lam_viec'] ?? [];
$lichTrinhTours = $data['lich_trinh_tours'] ?? [];
$currentMonth = $data['current_month'] ?? date('m');
$currentYear = $data['current_year'] ?? date('Y');

// Tính toán ngày đầu tháng và cuối tháng một cách an toàn
try {
    // Đảm bảo tháng có định dạng đúng (2 chữ số)
    $currentMonthPadded = str_pad($currentMonth, 2, '0', STR_PAD_LEFT);
    $currentMonthStart = new DateTime("{$currentYear}-{$currentMonthPadded}-01");
    $currentMonthEnd = new DateTime($currentMonthStart->format('Y-m-t')); // 't' trả về ngày cuối tháng
} catch (Exception $e) {
    // Fallback về tháng hiện tại nếu có lỗi
    $currentMonthStart = new DateTime();
    $currentMonthStart->modify('first day of this month');
    $currentMonthEnd = new DateTime($currentMonthStart->format('Y-m-t'));
}
?>

<main class="main-content">
    <div class="container-fluid">
        <!-- Breadcrumb -->
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="<?= BASE_URL_GUIDE ?>?act=lich-trinh">Lịch Trình</a></li>
                <li class="breadcrumb-item active">Lịch Làm Việc</li>
            </ol>
        </nav>

        <!-- Tiêu đề -->
        <div class="d-flex justify-content-between align-items-center mb-4">
            <div>
                <h1 class="page-title mb-1">📅 Lịch Làm Việc</h1>
                <div class="d-flex align-items-center">
                    <span class="text-muted">
                        <i class="fas fa-user mr-1"></i> <?= htmlspecialchars($guideInfo['ho_ten'] ?? '') ?>
                    </span>
                    <span class="text-muted ml-3">
                        <i class="fas fa-calendar-alt mr-1"></i> Tháng <?= $currentMonth ?>/<?= $currentYear ?>
                    </span>
                </div>
            </div>
            
            <div class="action-buttons">
                <!-- Chọn tháng/năm -->
                <div class="input-group input-group-sm" style="width: 200px;">
                    <input type="month" 
                           class="form-control" 
                           id="monthPicker"
                           value="<?= $currentYear . '-' . str_pad($currentMonth, 2, '0', STR_PAD_LEFT) ?>">
                    <div class="input-group-append">
                        <button class="btn btn-primary" onclick="changeMonth()">
                            <i class="fas fa-sync-alt"></i>
                        </button>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <!-- Lịch làm việc tháng -->
            <div class="col-lg-8">
                <div class="card">
                    <div class="card-header bg-primary text-white">
                        <h5 class="mb-0"><i class="fas fa-calendar mr-2"></i> Lịch Làm Việc Tháng</h5>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered">
                                <thead>
                                    <tr class="bg-light">
                                        <th style="width: 14%">Thứ 2</th>
                                        <th style="width: 14%">Thứ 3</th>
                                        <th style="width: 14%">Thứ 4</th>
                                        <th style="width: 14%">Thứ 5</th>
                                        <th style="width: 14%">Thứ 6</th>
                                        <th style="width: 14%">Thứ 7</th>
                                        <th style="width: 14%">Chủ nhật</th>
                                    </tr>
                                </thead>
                                <tbody id="calendarBody">
                                    <!-- Calendar will be generated by JavaScript -->
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Danh sách tour trong tháng -->
            <div class="col-lg-4">
                <div class="card mb-4">
                    <div class="card-header bg-success text-white">
                        <h5 class="mb-0"><i class="fas fa-list mr-2"></i> Tour Trong Tháng</h5>
                    </div>
                    <div class="card-body">
                        <?php if (empty($lichTrinhTours)): ?>
                            <div class="alert alert-info">Không có tour nào trong tháng này</div>
                        <?php else: ?>
                            <div class="list-group">
                                <?php foreach ($lichTrinhTours as $tour): ?>
                                    <?php 
                                    try {
                                        $tourStart = new DateTime($tour['ngay_bat_dau']);
                                        $tourEnd = new DateTime($tour['ngay_ket_thuc']);
                                        
                                        // Kiểm tra xem tour có trong tháng này không
                                        if ($tourStart <= $currentMonthEnd && $tourEnd >= $currentMonthStart):
                                    ?>
                                        <div class="list-group-item list-group-item-action mb-2">
                                            <div class="d-flex w-100 justify-content-between">
                                                <h6 class="mb-1"><?= htmlspecialchars($tour['ten_tour']) ?></h6>
                                                <small class="text-muted"><?= $tour['ma_tour'] ?></small>
                                            </div>
                                            <p class="mb-1 small">
                                                <i class="fas fa-calendar-alt mr-1"></i>
                                                <?= date('d/m/Y', strtotime($tour['ngay_bat_dau'])) ?> - <?= date('d/m/Y', strtotime($tour['ngay_ket_thuc'])) ?>
                                            </p>
                                            <small>
                                                <span class="badge badge-<?= 
                                                    $tour['trang_thai_lich'] == 'đang diễn ra' ? 'success' : 
                                                    ($tour['trang_thai_lich'] == 'đã hoàn thành' ? 'secondary' : 'primary')
                                                ?>">
                                                    <?= $tour['trang_thai_lich'] ?>
                                                </span>
                                                <?php if ($tour['ghi_chu_phan_cong']): ?>
                                                    <span class="badge badge-info ml-1">Có ghi chú</span>
                                                <?php endif; ?>
                                            </small>
                                        </div>
                                    <?php 
                                        endif;
                                    } catch (Exception $e) {
                                        // Bỏ qua tour có ngày không hợp lệ
                                        continue;
                                    }
                                    ?>
                                <?php endforeach; ?>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>

                <!-- Thống kê -->
                <div class="card">
                    <div class="card-header bg-info text-white">
                        <h5 class="mb-0"><i class="fas fa-chart-bar mr-2"></i> Thống Kê Tháng</h5>
                    </div>
                    <div class="card-body">
                        <?php
                        $countTour = 0;
                        $countBusy = 0;
                        $countOff = 0;
                        
                        foreach ($lichLamViec as $item) {
                            switch ($item['loai_lich']) {
                                case 'đã phân công':
                                    $countTour++;
                                    break;
                                case 'bận':
                                    $countBusy++;
                                    break;
                                case 'nghỉ':
                                    $countOff++;
                                    break;
                            }
                        }
                        ?>
                        <div class="text-center">
                            <div class="row mb-3">
                                <div class="col-6">
                                    <div class="bg-primary text-white rounded p-3">
                                        <h4 class="mb-0"><?= $countTour ?></h4>
                                        <small>Ngày có tour</small>
                                    </div>
                                </div>
                                <div class="col-6">
                                    <div class="bg-warning text-white rounded p-3">
                                        <h4 class="mb-0"><?= $countBusy ?></h4>
                                        <small>Ngày bận</small>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-6">
                                    <div class="bg-success text-white rounded p-3">
                                        <h4 class="mb-0"><?= $countOff ?></h4>
                                        <small>Ngày nghỉ</small>
                                    </div>
                                </div>
                                <div class="col-6">
                                    <div class="bg-secondary text-white rounded p-3">
                                        <h4 class="mb-0"><?= count($lichTrinhTours) ?></h4>
                                        <small>Tổng tour</small>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

<style>
.calendar-day {
    min-height: 100px;
    padding: 5px;
    position: relative;
    cursor: pointer;
    transition: all 0.3s;
}

.calendar-day:hover {
    background-color: #f8f9fa;
    transform: scale(1.02);
}

.calendar-date {
    font-size: 12px;
    font-weight: bold;
    color: #6c757d;
    margin-bottom: 5px;
}

.tour-event {
    background-color: #28a745;
    color: white;
    padding: 2px 5px;
    border-radius: 3px;
    font-size: 11px;
    margin-bottom: 2px;
    display: block;
}

.busy-event {
    background-color: #ffc107;
    color: black;
    padding: 2px 5px;
    border-radius: 3px;
    font-size: 11px;
    margin-bottom: 2px;
    display: block;
}

.off-event {
    background-color: #17a2b8;
    color: white;
    padding: 2px 5px;
    border-radius: 3px;
    font-size: 11px;
    margin-bottom: 2px;
    display: block;
}

.empty-day {
    background-color: #f8f9fa;
}

.other-month {
    background-color: #f8f9fa;
    color: #adb5bd;
}

.today {
    background-color: #e7f5ff;
    border: 2px solid #007bff;
}
</style>

<script>
// Biến toàn cục
let scheduleData = <?= json_encode($lichLamViec) ?>;
let tourData = <?= json_encode($lichTrinhTours) ?>;

// Tạo lịch tháng
function generateCalendar(year, month) {
    const calendarBody = document.getElementById('calendarBody');
    calendarBody.innerHTML = '';
    
    // Ngày đầu tiên của tháng
    const firstDay = new Date(year, month - 1, 1);
    // Ngày cuối cùng của tháng
    const lastDay = new Date(year, month, 0);
    // Ngày đầu tiên trong tuần (0 = Chủ nhật, 1 = Thứ 2)
    let startDay = firstDay.getDay();
    // Chuyển từ Chủ nhật = 0 sang Thứ 2 = 0
    startDay = startDay === 0 ? 6 : startDay - 1;
    
    // Tổng số ngày trong tháng
    const daysInMonth = lastDay.getDate();
    
    // Tính toán số tuần
    const totalCells = startDay + daysInMonth;
    const weeks = Math.ceil(totalCells / 7);
    
    let dayCounter = 1;
    let currentWeek = 0;
    
    for (let week = 0; week < weeks; week++) {
        const row = document.createElement('tr');
        
        for (let dayOfWeek = 0; dayOfWeek < 7; dayOfWeek++) {
            const cell = document.createElement('td');
            cell.className = 'calendar-day';
            
            // Tính ngày tháng cho ô hiện tại
            const cellIndex = (week * 7) + dayOfWeek;
            
            if (cellIndex < startDay || dayCounter > daysInMonth) {
                // Ô trống (tháng trước hoặc tháng sau)
                cell.className += ' other-month';
                
                // Tính ngày của tháng trước cho các ô đầu
                if (cellIndex < startDay) {
                    // Tính số ngày của tháng trước
                    const prevMonth = month - 1 === 0 ? 12 : month - 1;
                    const prevYear = month - 1 === 0 ? year - 1 : year;
                    const prevMonthLastDay = new Date(prevYear, prevMonth, 0).getDate();
                    const prevMonthDay = prevMonthLastDay - (startDay - cellIndex) + 1;
                    cell.innerHTML = `<div class="calendar-date">${prevMonthDay}</div>`;
                } else {
                    // Tính ngày của tháng sau cho các ô cuối
                    const nextMonthDay = cellIndex - startDay - daysInMonth + 1;
                    cell.innerHTML = `<div class="calendar-date">${nextMonthDay}</div>`;
                }
            } else {
                // Ngày trong tháng
                const currentDate = new Date(year, month - 1, dayCounter);
                const dateStr = currentDate.toISOString().split('T')[0];
                const isToday = isSameDay(currentDate, new Date());
                
                if (isToday) {
                    cell.className += ' today';
                }
                
                let content = `<div class="calendar-date">${dayCounter}</div>`;
                
                // Hiển thị sự kiện trong ngày
                const events = getEventsForDate(dateStr);
                events.forEach(event => {
                    let eventClass = '';
                    switch(event.type) {
                        case 'tour': eventClass = 'tour-event'; break;
                        case 'busy': eventClass = 'busy-event'; break;
                        case 'off': eventClass = 'off-event'; break;
                    }
                    content += `<span class="${eventClass}">${event.title}</span>`;
                });
                
                cell.innerHTML = content;
                cell.dataset.date = dateStr;
                cell.addEventListener('click', () => showDayDetail(dateStr));
                
                dayCounter++;
            }
            
            row.appendChild(cell);
        }
        
        calendarBody.appendChild(row);
        currentWeek++;
    }
}

// Lấy sự kiện cho một ngày cụ thể
function getEventsForDate(dateStr) {
    const events = [];
    
    // Kiểm tra lịch làm việc
    scheduleData.forEach(item => {
        if (item.ngay === dateStr) {
            events.push({
                type: getEventType(item.loai_lich),
                title: getEventTitle(item.loai_lich, item.ghi_chu)
            });
        }
    });
    
    // Kiểm tra tour
    tourData.forEach(tour => {
        try {
            const tourStart = new Date(tour.ngay_bat_dau);
            const tourEnd = new Date(tour.ngay_ket_thuc);
            const currentDate = new Date(dateStr);
            
            // Đặt giờ về 0 để so sánh chỉ ngày
            tourStart.setHours(0, 0, 0, 0);
            tourEnd.setHours(0, 0, 0, 0);
            currentDate.setHours(0, 0, 0, 0);
            
            if (currentDate >= tourStart && currentDate <= tourEnd) {
                events.push({
                    type: 'tour',
                    title: tour.ten_tour
                });
            }
        } catch (e) {
            console.error('Lỗi xử lý ngày tour:', e);
        }
    });
    
    return events;
}

// Chuyển loại lịch thành loại sự kiện
function getEventType(loaiLich) {
    switch(loaiLich) {
        case 'đã phân công': return 'tour';
        case 'bận': return 'busy';
        case 'nghỉ': return 'off';
        default: return 'busy';
    }
}

// Tạo tiêu đề sự kiện
function getEventTitle(loaiLich, ghiChu) {
    const titles = {
        'đã phân công': 'Có tour',
        'bận': 'Bận',
        'nghỉ': 'Nghỉ',
        'có thể làm': 'Có thể làm'
    };
    
    let title = titles[loaiLich] || loaiLich;
    if (ghiChu && ghiChu.length > 0) {
        title += ': ' + ghiChu.substring(0, 20);
    }
    
    return title;
}

// So sánh 2 ngày
function isSameDay(date1, date2) {
    return date1.getFullYear() === date2.getFullYear() &&
           date1.getMonth() === date2.getMonth() &&
           date1.getDate() === date2.getDate();
}

// Hiển thị chi tiết ngày
function showDayDetail(dateStr) {
    const date = new Date(dateStr);
    const formattedDate = date.toLocaleDateString('vi-VN', {
        weekday: 'long',
        year: 'numeric',
        month: 'long',
        day: 'numeric'
    });
    
    // Lấy sự kiện trong ngày
    const events = getEventsForDate(dateStr);
    
    let content = `<h5>${formattedDate}</h5>`;
    
    if (events.length === 0) {
        content += '<p class="text-muted">Không có sự kiện nào</p>';
    } else {
        content += '<ul class="list-group">';
        events.forEach(event => {
            content += `<li class="list-group-item">${event.title}</li>`;
        });
        content += '</ul>';
    }
    
    // Hiển thị modal
    const modal = new bootstrap.Modal(document.getElementById('dayDetailModal'));
    document.getElementById('modalTitle').innerHTML = formattedDate;
    document.getElementById('modalBody').innerHTML = content;
    modal.show();
}

// Thay đổi tháng
function changeMonth() {
    const monthPicker = document.getElementById('monthPicker');
    const [year, month] = monthPicker.value.split('-');
    
    window.location.href = `<?= BASE_URL_GUIDE ?>?act=lich-lam-viec&month=${month}&year=${year}`;
}

// Khởi tạo lịch khi trang load
document.addEventListener('DOMContentLoaded', function() {
    generateCalendar(<?= $currentYear ?>, <?= $currentMonth ?>);
});
</script>

<!-- Modal chi tiết ngày -->
<div class="modal fade" id="dayDetailModal" tabindex="-1" aria-labelledby="dayDetailModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalTitle">Chi tiết ngày</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="modalBody">
                <!-- Nội dung sẽ được thêm bằng JavaScript -->
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Đóng</button>
            </div>
        </div>
    </div>
</div>

<?php
include __DIR__ . '/../layout/footer.php';
?>